version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t udacitydevopsrt .
      - docker tag udacitydevopsrt:latest 947695616581.dkr.ecr.us-east-1.amazonaws.com/udacitydevopsrt:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 947695616581.dkr.ecr.us-east-1.amazonaws.com/udacitydevopsrt:latest
