version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t <your-image-name> .
      - docker tag <your-image-name>:latest <your-ecr-repository>:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push <your-ecr-repository>:latest
